version: "3.7"

services:
  superset:
    image: mdenari/superset_com_clickhouse:latest  #apache/superset:latest # Ou a versão específica que você está usando (ex: apache/superset:3.0.0)
    networks:
      - network_swarm_public
    environment:
      - SUPERSET_SECRET_KEY=Hyp3r1z3&@1
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres.kvllxokoaofajpvpcclb
      - DATABASE_PASSWORD=Hyp3r1z3&@3
      - DATABASE_HOST=aws-0-us-east-1.pooler.supabase.com
      - DATABASE_PORT=6543
    # ========================================================================
    # >>>>> ALTERAÇÕES AQUI <<<<<
    # O comando abaixo irá instalar os drivers e fixar as versões antes de iniciar o Superset
    # ========================================================================
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager01
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.superset.rule=Host(`superset.hyperize.com.br`)"
        - "traefik.http.routers.superset.entrypoints=websecure"
        - "traefik.http.routers.superset.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.superset.loadbalancer.server.port=8088"
      resources:
        limits:
          cpus: '1'
          memory: 1024M

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
